spring:
  application:
    name: post-service

  profiles:
    active: dev

  config:
    import: "optional:configserver:"

  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG-SERVER