name: Blog Web CI Pipeline
run-name: >
  Web CI - ${{ github.ref_name }} - ${{ github.actor }}

on:
  push:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'blog-web/**'
      - '.github/workflows/web-ci.yml'

concurrency:
  group: web-ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    #    name: Build Angular Application
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        working-directory: blog-web

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup, Run and Build
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: blog-web/package-lock.json

      - name: Install Dependencies
        run: npm ci

      #      - name: Lint source code
      #        run: npm run lint

      - name: Run unit test
        run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Build Angular application
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: blog-web/dist
          if-no-files-found: error
          retention-days: 7
