name: Blog Web CI Pipeline
run-name: >
  Web CI - ${{ github.ref_name }} - ${{ github.actor }}

on:
  push:
  pull_request:
    branches:
      - main
    paths:
      - 'blog-web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup, Run and Build
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci
      - run: npm run lint
      - run: npm test -- --watch=false --browsers=ChromeHeadless
      - run: npm run Build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: dist/
